version: '3.6'

services:

  # Backend API
  rewards-service:
    container_name: rewards-api
    build: ./
    command: npm start
    working_dir: /Workspace/fec-capstone/rewards
    env_file:
      - ./server/src/config/.env
    ports:
      - "3005:3005"
    environment:
      DATABASE_HOST: mysql
      MYSQL_URI: mysql://root:password@mysql:3307/kstart
      REDIS_URI: redis://redis:6380

  # MySQL
  mysql:
    image: mysql
    container_name: rewards-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kstart
      MYSQL_USER: k-user
      MYSQL_PASSWORD: k-pass
    ports:
      - "3307:3307"

  # Redis
  redis:
    image: redis
    container_name: rewards-redis
    ports:
      - "6380:6380"

